apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: <my-namespace>

resources:
  - api_deployment.yaml
  - api_pvc.yaml
  - api_service.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

configMapGenerator:
- name: oauth2-proxy-api-config
  files:
  - local.config.yml
