apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        # Automatically convert mounts to user group
        fsGroup: 1000
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.7.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 672M
          limits:
            cpu: 500m
            memory: 1024M
        args:
         - start
         - --import-realm
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_username
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_password
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_db_user
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_db_password
          #
          # https://www.keycloak.org/server/all-config#category-cache
          #
        - name: KC_CACHE
          value: local
          #
          # https://www.keycloak.org/server/all-config#category-feature
          #
        - name: KC_HEALTH_ENABLED
          value: "true"
          # https://www.keycloak.org/server/all-config#category-hostname_v2
        - name: KC_FEATURE_HOSTNAME
          value: v2
        - name: KC_HOSTNAME
          value: <my-host>
        - name: KC_PROXY_HEADERS
          value: xforwarded
        - name: KC_HTTP_ENABLED
          value: "true"
          # https://www.keycloak.org/server/all-config#category-database
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: keycloak-db
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_URL_DATABASE
          value: keycloak-data
        - name: KC_DB_SCHEMA
          value: public
        ports:
        - name: http
          containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /realms/master
        #     port: 8080
        volumeMounts:
        - name: realm-to-import-0
          mountPath: /opt/keycloak/data/import/realm-0.json
          subPath: realm-0.json
      volumes:
      - name: realm-to-import-0
        configMap:
          name: keycloak-realm
