apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-storage
spec:
  storageClassName: csi-nas
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
status: {}
