apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: <my-namespace>

resources:
  - db_service.yaml
  - db_statefulset.yaml
  - kc_deployment.yaml
  - kc_ingress.yaml
  - kc_service.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

configMapGenerator:
  - name: keycloak-realm
    files:
      - realm-0.json
