apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: <my-namespace>

resources:
  - api/
#  - csa/  # disabled because it's archived on 20.01.2026
  - dmi_data/
  - geoserver/
  - geosphere_data/
  - k8s-job-manager/
  - keycloak/
  - oauth2-proxy/
  - open-pioneer-trails/
  - secure_geoserver/
