apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# disabled because it's archived on 20.01.2026
#
#namespace: <my-namespace>
#
#resources:
#  - api_configmap.yaml
#  - api_deployment.yaml
#  - api_pvc.yaml
#  - api_service.yaml
#  - es_configmap.yaml
#  - es_service.yaml
#  - es_statefulset.yaml
#  - ingestor_cronjob.yaml
#  - ingestor_pvc.yaml
#  - ingress.yaml
#  - tsdb_configmap.yaml
#  - tsdb_service.yaml
#  - tsdb_statefulset.yaml
