apiVersion: batch/v1
kind: CronJob
metadata:
  name: dmi-ingest-dkss
spec:
  # every day at midnight
  # -> might be good to increase to four times
  #    a day according to the Storm Surge Model
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "job-dmi-ingestion-dkss"
            image: 52north/directed-dmi-ingestor:latest
            imagePullPolicy: Always
            env:
            - name: LOGURU_LEVEL
              value: INFO
            - name: DMI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dmi-user
                  key: key
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: name
            - name: BUCKET_KEY
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: key
            - name: BUCKET_SECRET
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: secret
            # command: ["/bin/sh"]
            # args: ["-c", "sleep 600"]
            resources:
              requests:
                memory: 450M
                cpu: 200m
              limits:
                memory: 450M
                cpu: 200m
          restartPolicy: Never
